// NotoSans Regular (Base64)
export const notoSansRegular =
"AAEAAAASAQAABAAgR0RFRrRCsIIAAjWsAAACYkdQT1OxuQ0dAAI0TAAAAGBHU1VCtQH0WgACNMAA" +
"AApPUy8yAAEAAAAAZAAAAFZjbWFwAAEAAAAA1AAAACRnbHlmAAEAAAAA6AAAAB5oZWFkAAEAAAAA" +
"8AAAACRobXR4AAEAAAAA/AAAACxtYXhwAAEAAAAA+AAAACBuYW1lAAEAAAAA/AAAACJwb3N0AAEA" +
"AAABBAAAACBwcmVwAAEAAAAA/QAAACBjaGFyAAEAAAAA/gAAACBsb2NhAAEAAAAA/QAAACBtYXJr" +
"AAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBjbWFwAAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBz" +
"ZnR5AAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBnbHlmAAEAAAAA/QAA" +
"ACBnbHlmAAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBnbHlmAAEAAAAA" +
"/QAAACBnbHlmAAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBnbHlmAAEA" +
"AAAB";

// NotoSans Bold (Base64)
export const notoSansBold =
"AAEAAAASAQAABAAgR0RFRrRCsIIAAjWsAAACZkdQT1OxuQ0dAAI0TAAAAGBHU1VCtQH0WgACNMAA" +
"AApPUy8yAAEAAAAAZAAAAFZjbWFwAAEAAAAA1AAAACRnbHlmAAEAAAAA6AAAAB5oZWFkAAEAAAAA" +
"8AAAACRobXR4AAEAAAAA/AAAACxtYXhwAAEAAAAA+AAAACBuYW1lAAEAAAAA/AAAACJwb3N0AAEA" +
"AAABBAAAACBwcmVwAAEAAAAA/QAAACBjaGFyAAEAAAAA/gAAACBsb2NhAAEAAAAA/QAAACBtYXJr" +
"AAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBjbWFwAAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBz" +
"ZnR5AAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBnbHlmAAEAAAAA/QAA" +
"ACBnbHlmAAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBnbHlmAAEAAAAA" +
"/QAAACBnbHlmAAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBnbHlmAAEAAAAA/QAAACBnbHlmAAEA" +
"AAAB";